DO NOT MERGE Disable tests due to NoSuchMethodError in CTS 15
android15-tests-dev includes unintended tests from aosp/main
due to the delay of setting up the aosp-24Q3-ts-dev branch.

These tests should be disabled because Android 15 doesn't have the
assoicated CLs or methods, because the test and system images were
snapped at the different time.

All these failures were found CTS 15 R2. Note that CTS 15 R1 didn't
have this issue.

The tests disabled are
org.apache.harmony.tests.java.util.TimerTest#test_scheduleAtFixedRateLjava_util_TimerTaskJJ_SkipMultipleMissedFixedRateTasks_newBehavior
org.apache.harmony.tests.java.util.TimerTest#test_scheduleAtFixedRateLjava_util_TimerTaskJJ_SkipMultipleMissedFixedRateTasks_oldBehavior
libcore.dalvik.system.VMRuntimeTest#testIsVTrunkStableFlagEnabled
libcore.dalvik.system.VMRuntimeTest#testIsM202409RampEnabled
test.java.util.concurrent.tck.ScheduledExecutorTest#testFixedRateSequenceSkipMultipleMissedFixedRateTasksDisabled
test.java.util.concurrent.tck.ScheduledExecutorTest#testFixedRateSequenceSkipMultipleMissedFixedRateTasksEnabled

Bug: 362424369
Bug: 362419059
Bug: 362449831
Bug: 362176487
Test: m cts
Merged-In: I20e4b7440095925fab4cc862a43b7a6311f6760b
Change-Id: Id3147ffc8552698fbb5218b8bfcad891cea2f109